runtime: nodejs10
service: default

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 1m


error_handlers:
  - file: _error.html
  - error_code: timeout
    file: _error.html

# index files
handlers:
- url: /(.+)/
  static_files: www/\1/index.html
  upload: www/(.+)/index.html
  require_matching_file: true

# site root
- url: /
  static_files: www/index.html
  upload: www/index.html
  require_matching_file: true

# For folders without trailing slashes - ideally a 301 redirect, but we're static & it isn't 2004
- url: /([^\.]+)([^/])
  static_files: www/\1\2/index.html
  upload: www/(.+)
  require_matching_file: true
  http_headers:
    Location: /?sss=(.+)

# Redirect Everything else
- url: /(.+)
  static_files: www/\1
  upload: www/(.+)
  require_matching_file: true

# Redirect Everything else
- url: .*
  static_files: _error.html
  upload: _error.html
  
